name: CI Pipeline
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  # Toolchain Versions
  GO_VERSION: "1.25"

  # CI Database Config (Only for testing inside GitHub Actions sidecar)
  TEST_DB_USER: test_user
  TEST_DB_PASS: test_password
  TEST_DB_NAME: test_db
  TEST_DB_HOST: localhost
  TEST_DB_PORT: 5432

jobs:
  app-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.app
          target: build
          load: true
          tags: 'my-app:build'
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Unit Tests
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.app
          target: test
          load: true
          tags: 'my-app:test'
          cache-from: type=gha
          cache-to: type=gha,mode=max

  web-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build Web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.proxy
          target: build
          load: true
          tags: 'my-web:build'
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Web
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.proxy
          target: test
          load: true
          tags: 'my-web:test'
          cache-from: type=gha
          cache-to: type=gha,mode=max

  migration-pipeline:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: ${{ env.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.TEST_DB_PASS }}
          POSTGRES_DB: ${{ env.TEST_DB_NAME }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          cache-dependency-path: app/go.sum

      - name: Install Migration Tools
        run: make install-tools

      - name: Verify SQLC Generation
        run: chmod +x scripts/verify_sqlc.sh && ./scripts/verify_sqlc.sh

      - name: Test Migrate Up & Down
        env:
          # Construct Connection String using global envs
          DB_URL: "postgres://${{ env.TEST_DB_USER }}:${{ env.TEST_DB_PASS }}@localhost:5432/${{ env.TEST_DB_NAME }}?sslmode=disable"
        run: |
          echo "Testing Migrations UP..."
          make migrate-up DB_URL="${{ env.DB_URL }}"
          echo "Testing Migrations DOWN..."
          make migrate-down DB_URL="${{ env.DB_URL }}"
          echo "Testing Re-Apply..."
          make migrate-up DB_URL="${{ env.DB_URL }}"

  security:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
#    needs: [app-pipeline, web-pipeline, migration-pipeline]
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'go', 'javascript' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          queries: security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{ matrix.language }}"

